### ISSUE TITLE
LinkTo element not receiving `turbo:submit-start` event

### ISSUE THREAD

**Issue by luizkowalski** [RoleModel/turbo-confirm#40]
I have places in my app where when the user submits a form, it shows a spinner for the extent of the submission, something like this:

```erb
 <%= link_to disconnect_calendar_path(calendar),
    data: {
    turbo_method: :post, turbo_confirm: 'Are you sure you want to disconnect this calendar?',
    confirm_button: "Disconnect"
  },
  class: class_names('absolute right-[18px] lg:right-[14px] top-[5px] lg:top-[13px] text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200') do %>
    <%= icon "x", library: :phosphor, class: "size-5" %>
  <% end %>
```

and it is hooked into a Stimulus controller to show/hide the spinner

```js
import { Controller } from '@hotwired/stimulus'

import { toggle } from 'el-transition'

export default class extends Controller {
  static targets = ['loader']

  connect () {
    this.element.addEventListener('turbo:submit-start', this.toggleSpinner.bind(this))
    this.element.addEventListener('turbo:submit-end', this.toggleSpinner.bind(this))
  }

  disconnect () {
    this.element.removeEventListener('turbo:submit-start', this.toggleSpinner.bind(this))
    this.element.removeEventListener('turbo:submit-end', this.toggleSpinner.bind(this))
  }

  toggleSpinner () {
    toggle(this.loaderTarget)
  }
}
```

now with turbo-confirm, when user accepts the dialog, the submission happens but `turbo:submit-start` doesn't trigger. I think that it maybe goes "behind" turbo's back if that makes sense and doesn't use "requestSubmit()". 

I tried hook into [confirm-accept](https://github.com/RoleModel/turbo-confirm/blob/635a934ec82948a2948d5de47a27f3b2d75255db/src/index.js#L12) but it didn't do anything. 

this is not really an issues, I'm just wondering if there's something that I can do to make this work as I want

**Comment by OutlawAndy** [comment]
Your issue is due to the limitations of using Turbo's "FormLink" behavior.  Switching to `button_to` should resolve the issue for you.  Something like:

```erb
<%= button_to disconnect_calendar_path(calendar), method: :post,
    data: {
    turbo_confirm: 'Are you sure you want to disconnect this calendar?',
    confirm_button: "Disconnect"
  },
  class: class_names('absolute right-[18px] lg:right-[14px] top-[5px] lg:top-[13px] text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200') do %>
    <%= icon "x", library: :phosphor, class: "size-5" %>
  <% end %>
```

It's because Turbo is dynamically appending a new form to the document body and submitting that.  It's that new form which receives the `turbo:submit-start` event, rather than your original link.

Alternatively, if you would prefer to use TurboConfirm's accept event as you mentioned trying.  The source code that you linked is somewhat misleading.  The event you need to listen for is actually `rms:confirm-accept`.  I've been meaning to document that.  Sorry for the confusion.

I'll wait for you to confirm that you've resolved this before closing this issue, so let me know if you still need help.

**Comment by luizkowalski** [comment]
hey, thank you so much for the clarification. `rms:confirm-accept` didn't help. I hooked into it but nothing gets printed in the console, like the event isn't emitted, and `button_to` _kind of_ worked. it creates a form inside a form and the outermost form gets posted, not the actual link I want, it just so happens that given the data, they work almost the same.

also, not sure that `rms:confirm-accept` would actually work since there is no "end" event for it, it would just show the spinner indefinitely. I could technically work around it by toggling for like 1 second only

**Comment by OutlawAndy** [comment]
ah, already being within a form is a good use case for `link_to` with a `data-turbo-method`...  Could you change your Stimulus controller to set those event listeners on `body` instead of `this.element`?

Sorry to send you in the wrong direction regarding `rms:confirm-accept`.  Now that I think about it, Turbo doesn't even provide a `submitter` in the case of a FormLink, so that approach was doomed as well..

**Comment by luizkowalski** [comment]
setting on the body works but any form submission toggles every spinner on the page hahaha

Honestly, this is not a big of a deal, more a nice-to-have, and if there's no easy way, I'm fine. It is purely cosmetics, and the endpoint finishes in around 150ms, so it doesn't bother me that much. 

I think this can be closed unless you want to spend time on it on a low-priority feature

I appreciate the help so far! happy 2025, Andy!

**Comment by OutlawAndy** [comment]
Thanks @luizkowalski , you too!
